#!/bin/sh
#create the vivado editor and launch vivado, exit just after launching
#xfce4-terminal -T "Vivado editor" --maximize -x tmux new-session -s Vivado -n info $HOME/.local/share/Xilinx/editor/info.sh
konsole -e 'tmux new-session -s Vivado -n info $HOME/.local/share/Xilinx/editor/info.sh' &
cd ~/Xilinx/Vivado/2019.2/bin/
./vivado
cd -

