#!/bin/bash

XDG_CONFIG_HOME="$HOME/.config"
source "$XDG_CONFIG_HOME/bash/variables.sh" #exportation de variables d'environement
source "$XDG_CONFIG_HOME/bash/completion.sh" #autocompletion de bash
source "$XDG_CONFIG_HOME/bash/color.sh" #alias collorés
source "$XDG_CONFIG_HOME/bash/prompt.sh" #prompt colloré
source "$XDG_CONFIG_HOME/bash/alias.sh" #alias perso
source "$XDG_CONFIG_HOME/bash/aliaslocal.sh" #alias local (racourcis...)
source "$XDG_CONFIG_HOME/bash/setting.sh" #paramètres perso comme l'éditeur
source "$XDG_CONFIG_HOME/bash/startup.sh" #programes à démarer automatiquement

