#!/bin/bash

source ~/.bash/completion.sh #autocompletion de bash
source ~/.bash/color.sh #alias collorés
source ~/.bash/prompt.sh #prompt colloré
source ~/.bash/alias.sh #alias perso
source ~/.bash/aliaslocal.sh #alias local (racourcis...)
source ~/.bash/setting.sh #paramètres perso comme l'éditeur
source ~/.bash/startup.sh #programes à démarer automatiquement

